import { ControlManager } from './controls.js';
import { AudioManager } from './audio.js';
import { canWalk, directionVector, findPath, shortestPathLength } from './collision.js';
import { getLevel } from './levels.js';
import { Player } from './player.js';
import { TrapManager } from './traps.js';
import { UI } from './ui.js';

export class Game {
  constructor(canvas) {
    this.canvas = canvas; this.ctx = canvas.getContext('2d'); this.tileSize = 48; this.audio = new AudioManager(); this.controls = new ControlManager(mode => this.notifyControlChange(mode)); this.player = new Player({ x: 1, y: 1 }); this.traps = new TrapManager(this); this.ui = new UI(this); this.levelIndex = 0; this.attempts = 3; this.accuracy = 100; this.lowAccuracyPresses = 0; this.moveCount = 0; this.targetMoves = 0; this.channelPhase = 0; this.mapSeed = Math.random(); this.levelVariation = 0; this.running = false; this.paused = false; this.lastTime = 0; this.status = 'SIGNAL STABLE'; this.oneWay = null; this.cheatBuffer = ''; this.bindInput(); this.loadLevel(0); }
  bindInput() { window.addEventListener('keydown', event => { this.recordCheatKey(event.key); if (['ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight'].includes(event.key)) { event.preventDefault(); this.input(event.key); } if (event.key === 'Enter' && !this.running) this.messageAction(); if (event.key === 'Escape' && this.running) this.togglePause(); }); }
  recordCheatKey(key) { if (!/^[a-z]$/i.test(key)) return; this.cheatBuffer = `${this.cheatBuffer}${key.toUpperCase()}`.slice(-8); if (this.cheatBuffer.endsWith('TEST')) this.testUnlock(); if (this.cheatBuffer.endsWith('WIN')) this.testWin(); if (this.cheatBuffer.endsWith('LIMIT')) this.testLimit(); }
  testUnlock() { this.cheatBuffer = ''; this.player.hasKey = true; this.player.setCheckpoint(this.level.start); this.status = 'TEST MODE: EXIT UNLOCKED'; this.ui.sync(this.state()); }
  testWin() { this.cheatBuffer = ''; if (!this.running) return; this.player.hasKey = true; this.moveCount = this.targetMoves; this.player.x = this.level.exit.x; this.player.y = this.level.exit.y; this.player.moving = false; this.checkTile(); }
  testLimit() { this.cheatBuffer = ''; if (!this.running) return; this.routeOverrun(); }
  loadLevel(index) { this.levelIndex = index; this.level = getLevel(index, this.levelVariation); if (!findPath(this.level)) throw new Error('Authored level failed solvability check'); this.targetMoves = shortestPathLength(this.level, this.level.start, this.level.key) + shortestPathLength(this.level, this.level.key, this.level.exit); this.moveCount = 0; this.lowAccuracyPresses = 0; this.channelPhase = 0; this.mapSeed = Math.random(); this.player.reset(this.level.start); this.traps.load(this.level); this.controls.resetControls(); this.oneWay = null; this.ui.sync(this.state()); this.draw(); }
  state() { return { level: this.levelIndex + 1, levelName: this.level.name, keys: this.player.hasKey ? 1 : 0, attempts: this.attempts, accuracy: this.accuracy, moves: this.moveCount, targetMoves: this.targetMoves, lowAccuracyPresses: this.lowAccuracyPresses, checkpoint: this.player.checkpoint !== this.level.start, checkpointName: this.player.checkpoint.x === this.level.start.x ? 'ORIGIN' : (this.level.checkpoints.find(point => point.x === this.player.checkpoint.x && point.y === this.player.checkpoint.y)?.name || 'ACTIVE'), status: this.status }; }
  start() { this.audio.unlock(); this.running = true; this.ui.hideStart(); this.lastTime = performance.now(); requestAnimationFrame(time => this.loop(time)); }
  loop(time) { if (!this.running) return; const delta = Math.min(50, time - this.lastTime); this.lastTime = time; if (!this.paused) { this.update(delta, time); this.draw(); } requestAnimationFrame(next => this.loop(next)); }
  update(delta, now) { this.player.update(); this.traps.update(delta); for (const item of this.controls.drain(now)) this.attemptMove(item.direction); if (!this.player.moving) this.checkTile(); }
  input(key) { if (!this.running || this.paused) return; if (this.player.moving) { this.ui.sync(this.state()); return; } if (this.accuracy === 1) { this.lowAccuracyPresses += 1; if (this.lowAccuracyPresses < 20) { this.status = `1% ACCURACY: ${this.lowAccuracyPresses}/20 PRESSES`; this.ui.sync(this.state()); return; } this.lowAccuracyPresses = 0; } const result = this.controls.resolve(key); if (!result) return; if (!result.queued) this.attemptMove(result.direction); else { this.status = 'INPUT DELAYED'; this.ui.sync(this.state()); } }
  attemptMove(direction) { if (this.oneWay && direction !== this.oneWay) { this.status = 'ONE WAY'; this.ui.sync(this.state()); return; } const [dx, dy] = directionVector(this.controls.applyTwist(direction, this.player.twist)); const x = this.player.tile.x + dx; const y = this.player.tile.y + dy; if (!canWalk(this.level, x, y) || this.traps.isWall(x, y)) { this.audio.tone(70, .04, 'square', .018); return; } this.moveCount += 1; if (this.moveCount > this.targetMoves) { this.routeOverrun(); return; } this.accuracy = Math.max(1, this.accuracy - 1); this.channelPhase = (this.channelPhase + 1) % 4; this.mapSeed = (this.mapSeed + .17) % 1; this.player.moveTo(x, y); this.player.twist = 'none'; this.status = this.accuracy === 1 ? '1% ACCURACY: 20 PRESSES PER MOVE' : `MOVE COST: 1% / CHANNEL SHIFT ${this.channelPhase + 1}/4`; this.audio.movement(); }
  checkTile() { const { x, y } = this.player.tile; this.traps.handleTile(x, y); if (this.level.key && x === this.level.key.x && y === this.level.key.y && !this.player.hasKey) { this.player.hasKey = true; this.audio.key(); this.status = 'KEY ACCEPTED'; this.notifyControlChange('KEY CHANGED THE RULES'); this.controls.setRotatedControls('right'); }
    if (x === this.level.exit.x && y === this.level.exit.y) { if (!this.level.requiresKey || this.player.hasKey) { if (this.moveCount === this.targetMoves) this.completeLevel(); else if (this.moveCount > this.targetMoves) this.routeOverrun(); else { this.status = `MORE MOVES NEEDED: ${this.targetMoves - this.moveCount}`; this.ui.sync(this.state()); } } else { this.status = 'EXIT LOCKED'; this.ui.sync(this.state()); } }
    this.ui.sync(this.state()); }
  activateCheckpoint(point) { if (this.player.checkpoint.x === point.x && this.player.checkpoint.y === point.y) return; this.player.setCheckpoint(point); this.audio.checkpoint(); this.status = 'CHECKPOINT ACTIVE'; this.ui.sync(this.state()); }
  changeControls(mode, seed = 0) { if (mode === 'REVERSED') this.controls.setReversedControls(); else if (mode === 'ROTATED_LEFT') this.controls.setRotatedControls('left'); else if (mode === 'ROTATED_RIGHT') this.controls.setRotatedControls('right'); else if (mode === 'MIRRORED') this.controls.setMirroredControls(); else if (mode === 'RANDOMIZED') this.controls.setRandomControls(seed || this.levelIndex + 1); }
  notifyControlChange(mode) { this.status = `SIGNAL: ${mode}`; this.audio.control(); this.ui.glitch(); this.ui.sync(this.state()); }
  teleport(destination) { this.player.x = destination.x; this.player.y = destination.y; this.player.moving = false; this.status = 'THE MAZE FOLDED'; this.ui.shake(); this.audio.control(); }
  damage(reason) { if (this.player.invulnerable) return; this.player.invulnerable = true; this.audio.trap(); this.ui.shake(); this.attempts -= 1; this.status = reason || 'TRAP ACTIVATED'; setTimeout(() => { this.player.invulnerable = false; if (this.attempts <= 0) this.gameOver(); else { this.mapSeed = Math.random(); this.player.respawn(); this.status = 'MAP PHASE SHIFTED'; this.ui.sync(this.state()); } }, 420); }
  completeLevel() { this.running = false; this.audio.complete(); if (this.levelIndex === 4) { this.ui.message('ESCAPE CONFIRMED', 'YOU BEAT THE PATTERN.', 'The maze was never random. It was waiting for you to notice.', 'PLAY AGAIN'); this.finished = true; } else { this.ui.message(`LEVEL ${this.levelIndex + 1} CLEARED`, 'THE MAZE BLINKED.', 'You found one of its rules. There are four more rooms.', 'NEXT LEVEL'); this.finished = false; } }
  gameOver() { this.running = false; this.audio.gameOver(); this.ui.message('ATTEMPTS EXHAUSTED', 'BETTER LUCK NEXT TIME, TWIN.', 'The maze only needed you to doubt the next key.', 'TRY AGAIN'); this.finished = true; }
  routeOverrun() { this.running = false; this.audio.gameOver(); this.ui.message('MOVE COUNT EXCEEDED', 'BETTER LUCK NEXT TIME, TWIN.', 'The exit required an exact route.', 'TRY AGAIN'); this.finished = true; }
  messageAction() { if (this.ui.messagePanel.hidden) return; this.ui.hideMessage(); if (this.finished) { this.levelIndex = 0; this.levelVariation = 0; this.attempts = 3; this.accuracy = 100; this.loadLevel(0); this.start(); } else { this.levelIndex += 1; this.levelVariation += 1; this.attempts = 3; this.loadLevel(this.levelIndex); this.start(); } }
  restartLevel() { this.attempts = 3; this.levelVariation += 1; this.loadLevel(this.levelIndex); this.ui.hideMessage(); this.audio.unlock(); this.lastTime = performance.now(); if (!this.running) { this.running = true; requestAnimationFrame(time => this.loop(time)); } }
  togglePause(force) { if (!this.running && force !== false) return; this.paused = force === undefined ? !this.paused : force; this.ui.pause(this.paused); }
  draw() { const size = this.tileSize; this.canvas.width = this.level.width * size + this.level.height * 18 + 100; this.canvas.height = this.level.height * size * .82 + 50; const ctx = this.ctx; ctx.setTransform(1, 0, 0, 1, 0, 0); ctx.clearRect(0, 0, this.canvas.width, this.canvas.height); ctx.fillStyle = '#0b1018'; ctx.fillRect(0, 0, this.canvas.width, this.canvas.height); ctx.save(); ctx.translate(48, 18); ctx.transform(1, 0, -.22, .82, 0, 0); for (let y = 0; y < this.level.height; y++) for (let x = 0; x < this.level.width; x++) this.drawTile(x, y, this.level.map[y][x] === '#'); this.drawEntrance(); this.drawFog(); this.drawChannels(); this.drawObjects(); ctx.restore(); }
  drawEntrance() { const ctx = this.ctx; const size = this.tileSize; const y = this.level.start.y * size; const end = this.level.start.x * size; const start = -size * 1.3; ctx.fillStyle = '#0a141b'; ctx.fillRect(start, y + 8, end - start, size - 16); ctx.strokeStyle = '#31505b'; ctx.globalAlpha = .85; ctx.strokeRect(start, y + 8, end - start, size - 16); ctx.strokeStyle = '#70f4df'; ctx.globalAlpha = .5; ctx.beginPath(); ctx.moveTo(start + 8, y + size / 2); ctx.lineTo(end - 8, y + size / 2); ctx.stroke(); ctx.globalAlpha = 1; }
  drawChannels() { const ctx = this.ctx; const size = this.tileSize; const tile = this.player.tile; const centerX = tile.x * size + size / 2; const centerY = tile.y * size + size / 2; const directions = [[0, -1], [1, 0], [0, 1], [-1, 0]]; ctx.save(); ctx.lineWidth = 2; directions.forEach(([dx, dy], index) => { if (!canWalk(this.level, tile.x + dx, tile.y + dy)) return; ctx.globalAlpha = index === this.channelPhase ? .55 : .18; ctx.strokeStyle = index === this.channelPhase ? '#70f4df' : '#35515b'; ctx.beginPath(); ctx.moveTo(centerX, centerY); ctx.lineTo(centerX + dx * size * .72, centerY + dy * size * .72); ctx.stroke(); }); ctx.restore(); }
  drawFog() { const ctx = this.ctx; const centerX = this.player.x * this.tileSize + this.tileSize / 2; const centerY = this.player.y * this.tileSize + this.tileSize / 2; const radius = this.tileSize * 2.7; ctx.save(); ctx.fillStyle = '#06090fc2'; ctx.fillRect(0, 0, this.canvas.width, this.canvas.height); ctx.globalCompositeOperation = 'destination-out'; const reveal = ctx.createRadialGradient(centerX, centerY, this.tileSize * .7, centerX, centerY, radius); reveal.addColorStop(0, 'rgba(0,0,0,1)'); reveal.addColorStop(.72, 'rgba(0,0,0,.82)'); reveal.addColorStop(1, 'rgba(0,0,0,0)'); ctx.fillStyle = reveal; ctx.beginPath(); ctx.arc(centerX, centerY, radius, 0, Math.PI * 2); ctx.fill(); ctx.restore(); }
  drawTile(x, y, wall) { const ctx = this.ctx; const size = this.tileSize; const depth = 6; const px = x * size; const py = y * size; const phase = Math.floor(this.mapSeed * 3); const wallColors = ['#121b24', '#181c27', '#122122']; const floorColors = [['#080f16', '#070c12'], ['#100d18', '#0b1018'], ['#081515', '#071111']][phase]; const texture = (x * 17 + y * 31 + phase * 13) % 5; if (wall) { ctx.fillStyle = '#060a10'; ctx.beginPath(); ctx.moveTo(px, py + size); ctx.lineTo(px + size, py + size); ctx.lineTo(px + size, py + size + depth); ctx.lineTo(px, py + size + depth); ctx.closePath(); ctx.fill(); ctx.fillStyle = wallColors[phase]; ctx.fillRect(px, py, size, size); ctx.fillStyle = '#25323d'; ctx.globalAlpha = .6; ctx.beginPath(); ctx.moveTo(px, py); ctx.lineTo(px + size, py); ctx.lineTo(px + size - 4, py + 4); ctx.lineTo(px + 4, py + 4); ctx.closePath(); ctx.fill(); ctx.globalAlpha = 1; ctx.strokeStyle = '#273640'; ctx.strokeRect(px + .5, py + .5, size - 1, size - 1); ctx.strokeStyle = '#16232d'; ctx.strokeRect(px + 6.5, py + 6.5, size - 13, size - 13); ctx.fillStyle = '#718694'; ctx.globalAlpha = .18; ctx.fillRect(px + 8, py + 9 + texture, size - 16, 1); ctx.globalAlpha = 1; } else { ctx.fillStyle = (x + y) % 2 ? floorColors[0] : floorColors[1]; ctx.fillRect(px, py, size, size); ctx.strokeStyle = '#1b2a34'; ctx.globalAlpha = .72; ctx.strokeRect(px + .5, py + .5, size - 1, size - 1); ctx.fillStyle = '#5c7179'; ctx.globalAlpha = .12; ctx.fillRect(px + 9 + texture * 2, py + 12, 2, 1); ctx.fillRect(px + 28, py + 32 - texture, 1, 2); ctx.globalAlpha = 1; } }
  drawObjects() { const ctx = this.ctx; const s = this.tileSize; const glow = (x, y, color, radius) => { const gradient = ctx.createRadialGradient(x, y, 1, x, y, radius); gradient.addColorStop(0, `${color}88`); gradient.addColorStop(1, `${color}00`); ctx.fillStyle = gradient; ctx.beginPath(); ctx.arc(x, y, radius, 0, Math.PI * 2); ctx.fill(); };
    const exit = this.level.exit; glow(exit.x * s + s / 2, exit.y * s + s / 2, '#a98bff', 32); ctx.strokeStyle = '#a98bff'; ctx.lineWidth = 2; ctx.strokeRect(exit.x * s + 12, exit.y * s + 12, s - 24, s - 24); ctx.fillStyle = '#a98bff'; ctx.font = '700 9px Space Mono'; ctx.fillText(this.player.hasKey ? 'OPEN' : 'LOCK', exit.x * s + 9, exit.y * s + 30);
    if (!this.player.hasKey) { const key = this.level.key; glow(key.x * s + s / 2, key.y * s + s / 2, '#f8b85e', 25); ctx.fillStyle = '#f8b85e'; ctx.beginPath(); ctx.arc(key.x * s + s / 2, key.y * s + s / 2, 6, 0, Math.PI * 2); ctx.fill(); ctx.fillRect(key.x * s + 25, key.y * s + 22, 12, 4); }
    this.traps.drawHints(ctx, s); for (const checkpoint of this.level.checkpoints) { ctx.strokeStyle = '#70f4df66'; ctx.strokeRect(checkpoint.x * s + 15, checkpoint.y * s + 15, s - 30, s - 30); }
    const px = this.player.x * s + s / 2; const py = this.player.y * s + s / 2; glow(px, py, '#70f4df', 42); ctx.fillStyle = '#05080d'; ctx.globalAlpha = .8; ctx.beginPath(); ctx.ellipse(px, py + 11, 13, 4, 0, 0, Math.PI * 2); ctx.fill(); ctx.globalAlpha = 1; const body = ctx.createRadialGradient(px - 4, py - 7, 1, px, py + 2, 18); body.addColorStop(0, '#f2fffd'); body.addColorStop(.3, '#70f4df'); body.addColorStop(1, '#08938f'); ctx.fillStyle = body; ctx.beginPath(); ctx.ellipse(px, py + 2, 12, 15, -.12, 0, Math.PI * 2); ctx.fill(); ctx.beginPath(); ctx.arc(px + 2, py - 10, 9, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#effffc'; ctx.globalAlpha = .85; ctx.beginPath(); ctx.arc(px - 2, py - 13, 4, 0, Math.PI * 2); ctx.fill(); ctx.globalAlpha = 1; ctx.fillStyle = '#071016'; ctx.beginPath(); ctx.arc(px + 6, py - 11, 2, 0, Math.PI * 2); ctx.fill(); }
}
